### ISSUE TITLE
[Tracking] サーバ本番稼動

### ISSUE THREAD

**Issue by lo48576** [pbl-2018-hillclimb/burning-pro-server#38]
* [x] Docker で使う rust のバージョンの更新 #44
* [x] burning-pro-server の安定稼動ブランチ (master) の用意 #47
* [x] DB 管理用 web UI の Basic 認証の実装 #35
